### ISSUE TITLE
Why did you block you?

### ISSUE THREAD

**Issue by KendallDoesCodingAlt** [waterflamev8/waterflamev8#2]
Bro, why did you block me, all I need is to talk to you urgently.. We haven't spoken from a long time

**Comment by KendallDoesCodingAlt1** [comment]
@waterflamev8 What did I do to you? Just tell me? Why did you block me for no reason man

**Comment by KendallDoesCodingAlt1** [comment]
I really need to talk

**Comment by KendallDoesCodingAlt1** [comment]
Thought we were friends

**Comment by KendallDoesCodingAlt1** [comment]
do you remember me?

**Comment by KendallDoesCodingAlt1** [comment]
I gave you discord nitro
